[project]
name = "neptunia-randomizer"
version = "0.1.0"
description = "Generate a random list of Neptunia character names"
requires-python = ">=3.14"
dependencies = ["pandas","streamlit"]

[dependency-groups]
dev = ["black"]