[project]
name = "neptunia-randomizer"
version = "0.2.0"
description = "Generate a random list of Neptunia character names"
requires-python = ">=3.14"
dependencies = [
    "pandas~=2.3.3",
    "streamlit~=1.53.1",
]

[dependency-groups]
dev = [
    "pandas-stubs~=2.3.3"
]
